"""
Generates data/gndec_facts.json — comprehensive curated Q&A for GNDEC RAG.
Run: python3 scraper/build_facts.py
"""
import json, os

FACTS = [

# ─── GENERAL ────────────────────────────────────────────────────────────────
{"question":"What is GNDEC?","answer":"Guru Nanak Dev Engineering College (GNDEC) is one of the oldest and most prestigious engineering institutions in Northern India, established in 1956 under the Nankana Sahib Education Trust (NSET). Located at Gill Road, Ludhiana, Punjab – 141006, it is affiliated to IKG Punjab Technical University (IKGPTU), Jalandhar, and approved by AICTE. It is the first engineering college in Punjab to be granted Autonomous status by UGC (2012, extended to 2032-33). The college is NAAC 'A' Grade accredited, NBA accredited for multiple programs, ISO 9001-2015 certified, and TCS accredited twice for placements. About 30,000 graduates and 7,500 post-graduates have passed out so far.","section":"About GNDEC","source_file":"gndec.ac.in"},

{"question":"When was GNDEC established and what is its history?","answer":"GNDEC was established in 1956 under the Nankana Sahib Education Trust (NSET), founded in memory of the sacred temple of Nankana Sahib, birthplace of Guru Nanak Dev Ji. The foundation stone was laid on 8th April 1956 by Late Dr. Rajendra Prasad, the first President of India. The Trust committed to admitting 70% students from rural areas every year. The college was initially affiliated to Punjab University, Chandigarh, and since 1997 to IKG Punjab Technical University (IKGPTU), Jalandhar. It received UGC Autonomous status in 2012 (extended to 2032-33), NAAC 'A' Grade accreditation, and has been ranked consistently within the top 50 engineering colleges nationally since 2006.","section":"History","source_file":"gndec.ac.in"},

{"question":"Where is GNDEC located and what are its contact details?","answer":"GNDEC is located at: Gill Road, Ludhiana, Punjab – 141006, India. Phone: 0161-2502240. Website: https://gndec.ac.in. Email: info@gndec.ac.in. Key portals: Admissions: admission.gndec.ac.in | Academics/Results: academics.gndec.ac.in | Exam: exam.gndec.ac.in | ERP: erp.gndec.ac.in | MOOC: mooc.gndec.ac.in | T&P Cell: tnpgndec.com","section":"Contact","source_file":"gndec.ac.in"},

{"question":"What is the NAAC and NBA accreditation status of GNDEC?","answer":"GNDEC has the following accreditations: NAAC Institutional Accreditation: 'A' Grade (Cycle 2, issued 31.08.2021, valid upto 30.08.2026). NBA Program Accreditation (Tier-I, Washington Accord): Mechanical Engineering – valid upto 30.06.2028; Civil Engineering – valid upto 30.06.2028; Information Technology – valid upto 30.06.2028; Computer Science & Engineering – valid upto 30.06.2028. Additional: ISO 9001-2015 certified, TCS accredited twice for placements, UGC Autonomous status (2012–2032-33), AICTE approved.","section":"Accreditation","source_file":"gndec.ac.in"},

# ─── PROGRAMS ───────────────────────────────────────────────────────────────
{"question":"What all programs does GNDEC offer?","answer":"GNDEC offers the following programs: UG Programs: B.Tech (CSE, IT, ECE, EE, ME, CE), B.Arch, BCA, BBA (from 2021, intake 60), B.Com Entrepreneurship (from 2024, intake 60), B.Voc (Interior Design). PG Programs: M.Tech (CSE, ECE, EE, ME, Production Engineering, Civil/Structural Engineering), MBA (2-year, intake 60, from 2007-08), MCA – 11 PG courses total. Research: Ph.D. in all Engineering branches and Management. QIP Centre (AICTE) for Ph.D. in Civil, Mechanical, and Electrical Engineering.","section":"Programs","source_file":"gndec.ac.in"},

{"question":"What B.Tech programs does GNDEC offer?","answer":"GNDEC offers B.Tech (4-year, 8 semesters) in: 1) Computer Science & Engineering (CSE) – est. 1997, 2) Information Technology (IT) – est. 2001, 3) Electronics & Communication Engineering (ECE), 4) Electrical Engineering (EE), 5) Mechanical Engineering (ME), 6) Civil Engineering (CE). All programs are affiliated to IKGPTU Jalandhar, approved by AICTE, and conducted under UGC Autonomous status. CSE, IT, ME, and CE are NBA accredited (Tier-I).","section":"B.Tech Programs","source_file":"gndec.ac.in"},

{"question":"What M.Tech programs does GNDEC offer?","answer":"GNDEC offers M.Tech (2-year) in: Computer Science & Engineering, Electronics & Communication Engineering, Electrical Engineering, Mechanical Engineering, Production Engineering, Civil Engineering (Structural Engineering). Admission is through GATE scores via PTU counselling.","section":"M.Tech Programs","source_file":"gndec.ac.in"},

{"question":"What is the MBA program at GNDEC?","answer":"GNDEC's Department of Business Administration offers MBA (Master of Business Administration) – 2-year full-time program, intake 60 students, started from academic session 2007-08. Also offers BBA (3-year, intake 60, from 2021) and B.Com Entrepreneurship (3-year, intake 60, from 2024). All programs affiliated to IKGPTU and approved by AICTE. Admission helpline: 9815903230, 9417992553.","section":"MBA Program","source_file":"mba.gndec.ac.in"},

{"question":"What is the MCA program at GNDEC?","answer":"GNDEC offers MCA (Master of Computer Applications) – postgraduate program covering programming, databases, software engineering, networking, and emerging technologies. Admission through NIMCET or state-level entrance exams. Admission helpline: 9876700810, 9417271184.","section":"MCA Program","source_file":"mca.gndec.ac.in"},

# ─── ADMISSIONS ─────────────────────────────────────────────────────────────
{"question":"What is the admission process at GNDEC for 2026-27?","answer":"GNDEC Admissions 2026-27: B.Tech/M.Tech: JEE Main scores + Punjab State merit via IKGPTU counselling. Lateral Entry B.Tech (2nd year): Diploma/B.Sc marks. MBA/BBA: CAT/MAT/CMAT scores via PTU counselling. MCA/BCA: NIMCET or state-level entrance. B.Arch: NATA scores. B.Voc/B.Com: Merit-based. Registration: Pay Rs. 250 as user creation charges on admission.gndec.ac.in. Exam fee: Rs. 350 for entrance tests at college. Sikh Religion Examination (SRE)-2026 also announced. Visit: admission.gndec.ac.in","section":"Admissions 2026-27","source_file":"admission.gndec.ac.in"},

{"question":"What are the admission helpline numbers at GNDEC?","answer":"GNDEC Admission Helpline Numbers (2026-27): B.Tech & M.Tech: 9041495448, 8968553073, 7696771769, 7710610448. BBA, B.Com & MBA: 9815903230, 9417992553. BCA & MCA: 9876700810, 9417271184. B.Arch & B.Voc: 8427866335, 7696521055. B.Tech Working Professionals (CE): 9465196630. B.Tech Working Professionals (ME): 9914255011. Sikh Religion Exam: 9041464904. PMS Scholarship: 9041557904. WhatsApp Helpline: 73472-00448.","section":"Admission Helpline","source_file":"admission.gndec.ac.in"},

{"question":"What documents are required for admission at GNDEC?","answer":"For GNDEC admission, the following documents are typically required: 10th and 12th mark sheets and certificates, JEE Main scorecard (for B.Tech), Entrance exam scorecard (for MBA/MCA), Category certificate (SC/ST/OBC if applicable), Domicile/Residence certificate of Punjab, Character certificate from last institution, Migration certificate, Medical fitness certificate, Passport-size photographs, Aadhaar card. Detailed checklist available at admission.gndec.ac.in/important_notices.php.","section":"Admission Documents","source_file":"admission.gndec.ac.in"},

{"question":"What is the rural area quota at GNDEC?","answer":"GNDEC has a founding commitment to reserve 70% of seats for students from Rural Areas. This is not a government-mandated quota but a commitment made by the Nankana Sahib Education Trust (NSET) when the college was established on 8th April 1956. The Trust deed registered on 24th February 1953 specifically committed to 'uplift the vast weaker section of Indian polity comprising Rural India by admitting 70% students every year from Rural Areas.' This commitment was made to the nation on the day the foundation stone was laid by the First President of India, Dr. Rajendra Prasad Ji. Students from rural areas of Punjab are given preference in admissions under this institutional policy.","section":"Rural Quota","source_file":"gndec.ac.in"},

{"question":"What is the eligibility criteria for B.Tech admission at GNDEC?","answer":"B.Tech Eligibility at GNDEC: Minimum 45% marks in 10+2 (Class 12) for General category students. Subjects: Physics and Mathematics as compulsory, plus one of Chemistry, Computer Science, Biology, or Biotechnology. Entrance exam: JEE Main score required for PTU counselling. Total B.Tech seat intake: 1035 seats across all branches. Total tuition fees: approximately Rs. 2.4 Lakh (total program). For reserved category students, relaxation in minimum marks as per Punjab government norms applies.","section":"B.Tech Eligibility","source_file":"gndec.ac.in"},

{"question":"What is the eligibility criteria for MBA admission at GNDEC?","answer":"MBA Eligibility at GNDEC: Bachelor's degree of minimum 3-year duration in any discipline with minimum 50% marks (45% for reserved category). Entrance exam: CMAT score required. Seat intake: 60 seats. Total tuition fees: approximately Rs. 1.2 Lakh (total program). In case seats are not filled under respective categories, admission is considered on basis of inter-se-merit in qualifying examination.","section":"MBA Eligibility","source_file":"gndec.ac.in"},

{"question":"What is the eligibility criteria for M.Tech admission at GNDEC?","answer":"M.Tech Eligibility at GNDEC: B.E./B.Tech in relevant branch with minimum 50% marks (45% for reserved category). Entrance exam: GATE score required via CCMT counselling. Seat intake: 313 seats across all M.Tech programs. Total tuition fees: approximately Rs. 78,000 (total program). AMIE/AMIETE graduates with 55%+ marks and 2 years experience after B.Tech are also eligible. GATE COAP 2026 registration is active.","section":"M.Tech Eligibility","source_file":"gndec.ac.in"},

{"question":"What is the eligibility criteria for MCA admission at GNDEC?","answer":"MCA Eligibility at GNDEC: Bachelor's degree with minimum 50% marks. M.Sc. in IT/CS with Mathematics as a course at 10+2, graduation, or PG level are eligible. Entrance exam: PTU MCA entrance exam. Seat intake: 60 seats. Total tuition fees: approximately Rs. 1.2 Lakh (total program). Admission through PTU MCA counselling.","section":"MCA Eligibility","source_file":"gndec.ac.in"},

{"question":"What is the eligibility criteria for B.Arch admission at GNDEC?","answer":"B.Arch Eligibility at GNDEC: 10+2 with minimum 50% marks for General category. Mathematics as compulsory subject. Entrance exam: NATA (National Aptitude Test in Architecture) score required. Also accepts 10+3 Diploma with Mathematics (50% marks). Seat intake: 40 seats. Total tuition fees: approximately Rs. 3 Lakh (total program). NATA 2026 Phase 1 exam: April 4 – June 13, 2026. Phase 2: August 7-8, 2026.","section":"B.Arch Eligibility","source_file":"gndec.ac.in"},

{"question":"What is the total seat intake at GNDEC?","answer":"GNDEC total seat intake: B.Tech: 1035 seats (across CSE, IT, ECE, EE, ME, CE). M.Tech: 313 seats (across all specializations). MBA: 60 seats. MCA: 60 seats. B.Arch: 40 seats. BBA: 60 seats. B.Com Entrepreneurship: 60 seats. Ph.D.: 60 seats. PG Diploma: 20 seats. Total combined seats: approximately 1375 seats. GNDEC offers 44 programs in total.","section":"Seat Intake","source_file":"gndec.ac.in"},

# ─── FEE STRUCTURE ──────────────────────────────────────────────────────────
{"question":"What is the fee structure at GNDEC?","answer":"GNDEC Fee Structure (Session Jan–Jun 2026, subject to revision): Fee notices for all branches (B.Tech, MBA, MCA, BCA, BBA, B.Voc, B.Com, M.Tech, Ph.D) are available at gndec.ac.in under Student Corner. Approximate annual fees: B.Tech – Rs. 70,000–80,000 per year; MBA – Rs. 60,000–70,000 per year; MCA – Rs. 50,000–60,000 per year. Fees are regulated by Punjab government and IKGPTU. Online payment available through the college portal. For exact current fees, visit gndec.ac.in or contact the accounts office.","section":"Fee Structure","source_file":"gndec.ac.in"},

{"question":"How to pay semester fee at GNDEC?","answer":"GNDEC semester fee can be paid online through the college payment portal. Fee Notice for Session January–June 2026 is available on gndec.ac.in (Student Corner). Payment tips: Do not click close/refresh/back during payment. UPI payments: wait 2-5 working days for acknowledgement. If amount is debited but transaction shows incomplete, it will be reversed in 7-10 working days (excluding Sundays and National Holidays). For refund of successful payment, download the refund format from the college website.","section":"Fee Payment","source_file":"gndec.ac.in"},

{"question":"Is there a fee notice for Ph.D students at GNDEC?","answer":"Yes, GNDEC has issued a separate Fee Notice for Ph.D Students for the session January–June 2026. This is available in the Student Corner section of gndec.ac.in. Ph.D students should check the notice for exact fee amounts and payment deadlines.","section":"Ph.D Fee","source_file":"gndec.ac.in"},

# ─── SCHOLARSHIPS ───────────────────────────────────────────────────────────
{"question":"What scholarships are available at GNDEC?","answer":"Scholarships available at GNDEC: 1) Punjab Government Post-Matric Scholarship for SC/ST/OBC students (apply via NSP portal). 2) PMS (Post-Matric Scholarship) – helpline: 9041557904. 3) Alumni Scholarship for needy and academically sound students of GNDEC (2026 notice active). 4) AICTE Fellowship/Scholarship for PG students. 5) Merit-based scholarships for top performers. 6) Central Government scholarships via National Scholarship Portal (NSP). 7) Fee concessions for economically weaker sections. 8) Minority scholarships for eligible students. For scholarship queries, contact: 9041557904.","section":"Scholarships","source_file":"gndec.ac.in"},

{"question":"How to apply for PMS scholarship at GNDEC?","answer":"For PMS (Post-Matric Scholarship) at GNDEC: Apply through the National Scholarship Portal (NSP) at scholarships.gov.in. Required documents: income certificate, caste certificate, bank account details, previous year mark sheets, Aadhaar card. Helpline at GNDEC for PMS scholarship queries: 9041557904. Deadline and exact procedure are announced each academic year on the college notice board and website.","section":"PMS Scholarship","source_file":"gndec.ac.in"},

{"question":"Is there an alumni scholarship at GNDEC?","answer":"Yes, GNDEC has an Alumni Scholarship for needy and academically sound students. The 2026 scholarship notice has been issued. This scholarship is funded by GNDEC alumni to support deserving students. Details and application forms are available on gndec.ac.in under Student Corner.","section":"Alumni Scholarship","source_file":"gndec.ac.in"},

# ─── FACULTY ────────────────────────────────────────────────────────────────
{"question":"Who is the Head of the IT Department at GNDEC?","answer":"Dr. Kulvinder Singh Mann is the Head of the Department of Information Technology (IT) at GNDEC. The IT department was established in 2001 and offers B.Tech in Information Technology.","section":"IT Faculty","source_file":"it.gndec.ac.in"},

{"question":"Tell me about the faculty at GNDEC CSE department","answer":"The CSE Department at GNDEC (established 1997) has experienced faculty with expertise in AI, ML, cloud computing, cybersecurity, and software engineering. The department offers B.Tech and M.Tech in CSE. Faculty members are actively involved in research and have published in national and international journals. The department has produced notable alumni at companies like Apple, Microsoft, Salesforce, Accenture, Nokia, and NetApp. For current faculty list, visit cse.gndec.ac.in.","section":"CSE Faculty","source_file":"cse.gndec.ac.in"},

{"question":"What is the faculty strength at GNDEC?","answer":"GNDEC has a large and experienced faculty across all departments. The college has Ph.D. qualified professors, associate professors, and assistant professors in all engineering and management disciplines. Faculty members are engaged in research funded by DST, AICTE, and other agencies. The college has a QIP (Quality Improvement Programme) centre under AICTE for faculty pursuing Ph.D. in Civil, Mechanical, and Electrical Engineering. For department-wise faculty lists, visit the respective department websites (e.g., cse.gndec.ac.in, it.gndec.ac.in, ece.gndec.ac.in).","section":"Faculty","source_file":"gndec.ac.in"},

# ─── RECENT EVENTS & NOTICES ────────────────────────────────────────────────
{"question":"What are the recent events and notices at GNDEC?","answer":"Recent notices and events at GNDEC (2025-26): 1) Harmony 2025 – Annual College Magazine released. 2) College Newsletter 2024 (Vol. 12) published. 3) Sikh Religion Examination (SRE)-2026 announced. 4) Alumni Scholarship for needy students 2026 – applications open. 5) Fee Notice Jan–Jun 2026 issued for all branches. 6) Job/Appointment advertisement posted (check gndec.ac.in/?q=jobs). 7) GNDEC e-Library App launched (available on Google Play Store and Apple Store). 8) Knimbus Digital Library – self-registration for remote access available. 9) Awareness about National Cyber Crime Portal. 10) GNE Alumni Australasia Inc. established. For latest notices, visit gndec.ac.in notice board.","section":"Recent Events","source_file":"gndec.ac.in"},

{"question":"What is Harmony at GNDEC?","answer":"Harmony is the Annual College Magazine of GNDEC. Harmony 2025 has been released. It showcases student achievements, department activities, cultural events, sports, and college life. The magazine is a platform for students to express their creativity through articles, poems, and artwork.","section":"Harmony Magazine","source_file":"gndec.ac.in"},

{"question":"What is the GNDEC e-Library App?","answer":"GNDEC has launched an e-Library App available on Google Play Store and Apple Store. Students can also access the Knimbus Digital Library remotely by self-registering for off-campus access. The library provides access to national and international journals, e-books, and research databases.","section":"e-Library","source_file":"gndec.ac.in"},

{"question":"Are there any job openings at GNDEC?","answer":"GNDEC periodically posts faculty and staff recruitment advertisements. Current job openings are posted at gndec.ac.in/?q=jobs. The advertisement and general instructions for candidates are available as downloadable PDFs on the website. Check the notice board regularly for new openings.","section":"Job Openings","source_file":"gndec.ac.in"},

# ─── DEPARTMENTS ────────────────────────────────────────────────────────────
{"question":"Tell me about the CSE department at GNDEC","answer":"Department of Computer Science & Engineering (CSE) at GNDEC: Established in 1997. Offers B.Tech CSE (NBA accredited, Tier-I, valid upto 2028) and M.Tech CSE. State-of-the-art computer labs, departmental library, outcome-based education curriculum. Active societies: Computer Society of India (CSI), Data Science Club. Notable alumni at Apple, Microsoft, Salesforce, Accenture, Nokia, NetApp, and government organizations. Strong placement record. For details: cse.gndec.ac.in.","section":"CSE Department","source_file":"cse.gndec.ac.in"},

{"question":"Tell me about the IT department at GNDEC","answer":"Department of Information Technology (IT) at GNDEC: Established in 2001. Offers B.Tech IT (NBA accredited, Tier-I, valid upto 2028). Head of Department: Dr. Kulvinder Singh Mann. Mission: impart high-quality UG/PG education and leading-edge research in IT. Well-equipped computing labs, departmental library. Focuses on software development, networking, and emerging technologies. For details: it.gndec.ac.in.","section":"IT Department","source_file":"it.gndec.ac.in"},

{"question":"Tell me about the ECE department at GNDEC","answer":"Department of Electronics & Communication Engineering (ECE) at GNDEC: Offers B.Tech ECE and M.Tech ECE. Labs for digital electronics, communication systems, VLSI, and embedded systems. Active IETE Students Forum (ISF). Publishes department newsletter (Newsletter 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017 available). Strong research activities and industry collaborations. For details: ece.gndec.ac.in.","section":"ECE Department","source_file":"ece.gndec.ac.in"},

{"question":"Tell me about the EE department at GNDEC","answer":"Department of Electrical Engineering (EE) at GNDEC: Offers B.Tech EE and M.Tech EE. Covers power systems, control systems, electrical machines, and power electronics. Well-equipped labs and experienced faculty. For details: ee.gndec.ac.in.","section":"EE Department","source_file":"ee.gndec.ac.in"},

{"question":"Tell me about the ME department at GNDEC","answer":"Department of Mechanical Engineering (ME) at GNDEC: Offers B.Tech ME (NBA accredited, Tier-I, valid upto 2028) and M.Tech in ME and Production Engineering. Labs for manufacturing, CAD/CAM, thermodynamics, and fluid mechanics. Strong industry connections with manufacturing companies in Ludhiana. Also offers B.Tech for Working Professionals (helpline: 9914255011). For details: me.gndec.ac.in.","section":"ME Department","source_file":"me.gndec.ac.in"},

{"question":"Tell me about the Civil Engineering department at GNDEC","answer":"Department of Civil Engineering (CE) at GNDEC: Offers B.Tech CE (NBA accredited, Tier-I, valid upto 2028) and M.Tech in Structural Engineering. Also offers B.Tech for Working Professionals (helpline: 9465196630). Covers structural engineering, geotechnical engineering, transportation, and environmental engineering. Vision: to establish an outstanding centre of regional and national reputation for quality engineering education. For details: ce.gndec.ac.in.","section":"CE Department","source_file":"ce.gndec.ac.in"},

{"question":"Tell me about the MBA/BBA department at GNDEC","answer":"Department of Business Administration at GNDEC: Offers MBA (2-year, intake 60, from 2007-08), BBA (3-year, intake 60, from 2021), B.Com Entrepreneurship (3-year, intake 60, from 2024). All affiliated to IKGPTU and approved by AICTE. Focus on quality professional education for managerial roles. Admission helpline: 9815903230, 9417992553. For details: mba.gndec.ac.in.","section":"MBA Department","source_file":"mba.gndec.ac.in"},

# ─── PLACEMENTS ─────────────────────────────────────────────────────────────
{"question":"What is the placement record of GNDEC?","answer":"GNDEC has an excellent placement record. The Training and Career Cell (TCC) coordinates all placement activities. GNDEC has been declared Best Engineering College by IKGPTU in 2011, 2012, and 2014 for excellent placements. TCS has accredited GNDEC twice for placement quality. Major recruiters include TCS, Infosys, Wipro, HCL, Accenture, Microsoft, Apple, Salesforce, Nokia, NetApp, and manufacturing companies from the Ludhiana industrial belt. TCC portal: tnpgndec.com.","section":"Placements","source_file":"tcc.gndec.ac.in"},

{"question":"What companies recruit from GNDEC?","answer":"Major companies that recruit from GNDEC include: IT sector: TCS, Infosys, Wipro, HCL, Accenture, Microsoft, Apple, Salesforce, Nokia, NetApp, Aurea Software, Cloudworks, AppSmartz, KWA Analytics. Manufacturing: Hero Honda, Bajaj Sons, SML Isuzu, Boeing (alumni). Government/PSU: Indian Railways, PSPCL, Nuclear Power Corporation, Delhi Power Board, Indian Army, Delhi Police (IPS). GNDEC alumni are serving globally in eminent companies, academia, and public sector.","section":"Recruiters","source_file":"tcc.gndec.ac.in"},

# ─── CAMPUS LIFE ────────────────────────────────────────────────────────────
{"question":"What hostel facilities are available at GNDEC?","answer":"GNDEC provides separate hostel facilities for boys and girls. Amenities include furnished rooms, mess facility, Wi-Fi, sports facilities, and 24-hour security. Helpline for hostel-related enquiries available. Anti-ragging squads are active. Shakti App available for women's safety. Notice and Complaint Form for Caste-Based Discrimination available. Grievance Redressal Committee (GRC) for students and staff. 24-hour anti-ragging helpline numbers available on college website.","section":"Hostel","source_file":"gndec.ac.in"},

{"question":"What sports facilities are available at GNDEC?","answer":"GNDEC has excellent sports facilities. The college is the overall sports champion of IKGPTU. Outdoor sports: cricket, football, hockey, athletics. Indoor sports: table tennis, badminton, chess, carrom. The college has a dedicated sports department and participates in inter-college and university-level competitions. NCC has 106 cadets (79 boys, 27 girls). NSS has 350 volunteers with 1000+ enrolled annually.","section":"Sports","source_file":"gndec.ac.in"},

{"question":"Does GNDEC have an FM radio station?","answer":"Yes, GNDEC has its own FM Radio Station broadcasting on FM 90.8. It is one of the unique facilities of the college, providing a platform for student creativity and campus communication.","section":"FM Radio","source_file":"gndec.ac.in"},

{"question":"What is the NCC and NSS at GNDEC?","answer":"GNDEC has active NCC (National Cadet Corps) and NSS (National Service Scheme) units. NCC: 106 cadets (79 boys, 27 girls) – develops discipline, leadership, and patriotism. NSS: 350 volunteers with 1000+ enrolled annually – focuses on community service and social development. Both units participate in camps, parades, and social service activities.","section":"NCC NSS","source_file":"gndec.ac.in"},

{"question":"What cultural activities are there at GNDEC?","answer":"GNDEC has an active cultural scene: Harmony 2025 – Annual College Magazine. College Newsletter 2024 (Vol. 12). Cultural committee organizes youth festivals, open competitions, and student committee activities. Students participate in inter-college cultural competitions at state and national levels. The college has a rich tradition of cultural events celebrating diversity and talent.","section":"Cultural Activities","source_file":"gndec.ac.in"},

# ─── INFRASTRUCTURE ─────────────────────────────────────────────────────────
{"question":"What infrastructure does GNDEC have?","answer":"GNDEC has modern infrastructure: Departmental laboratories (state-of-the-art in all departments), Central library with Knimbus Digital Library access, e-Library App (Google Play/Apple Store), Computer centers with high-speed internet, Separate boys and girls hostels, Sports complex (overall IKGPTU sports champion), Canteen and cafeteria, Medical facilities, Auditorium and seminar halls, Wi-Fi enabled campus, FM Radio Station (FM 90.8), ERP system (erp.gndec.ac.in), MOOC portal (mooc.gndec.ac.in).","section":"Infrastructure","source_file":"gndec.ac.in"},

# ─── NOTABLE ALUMNI ─────────────────────────────────────────────────────────
{"question":"Who are the notable alumni of GNDEC?","answer":"Notable GNDEC alumni (from official records): Mechanical Engineering: Er. Rahul Sharma (2006, Chief Engineer, Brookhaven National Lab, USA), Dr. Satbir Singh (2000, Faculty, Carnegie Mellon University, USA), Er. Gagandeep Singh Grewal (1996, Structural Design Engineer, Boeing, USA), Dr. H.S. Shan (1966, Ex-Professor & Head, IIT Roorkee). Electrical Engineering: Er. Madhur Verma IPS (2001, DCP Delhi Police), Air Marshal RKS Shera (1980, AQ Commanding-in-Chief, Indian Air Force), Er. G.S. Sandhu IAS (1975, Ex-Principal Secretary, Technical Education Rajasthan). Civil Engineering: Er. Sukh Dhaliwal (1979, Member of Parliament, Canada), Er. Girdhari Lal Goel (1982, Chief Engineer, Indian Railways). ECE: Er. Karan Bajwa (1988, Managing Director, IBM India), Dr. Ajay Kumar Sharma (1985, Vice-Chancellor, IKG PTU), Er. Amandeep Singh Litt (1991, Group CTO, Axiata Group, Malaysia). CSE: Er. Parminder Singh Sandhu (2001, IT Security Engineer, Apple Inc.), Er. Avneep Singh Dhanju (2004, Software Engineer, Microsoft), Er. Shruti Sharma IAS (2003, Indian Administrative Services). IT: Er. Manjeet Singh Bhatia (2008, Senior Software Engineer, Intel Corporation, USA), Er. Harleen Juneja (2003, Program Manager, Google, USA). About 30,000 graduates and 7,500 post-graduates have passed out.","section":"Alumni","source_file":"gndec.ac.in"},

# ─── RANKINGS ───────────────────────────────────────────────────────────────
{"question":"What is the ranking of GNDEC?","answer":"GNDEC rankings: Ranked consistently within the top 50 engineering colleges nationally since 2006 (India Today, Outlook, CSR, Star TV surveys). NIRF Rank Band: 200-250 (2021). Declared Best Engineering College by IKGPTU in 2011, 2012, and 2014 for excellent placements. Overall sports champion of IKGPTU. First engineering college in Punjab to receive UGC Autonomous status (2012).","section":"Rankings","source_file":"gndec.ac.in"},

# ─── EXAMS & RESULTS ────────────────────────────────────────────────────────
{"question":"How to check results at GNDEC?","answer":"GNDEC exam results can be checked at: academics.gndec.ac.in (for students) and exam.gndec.ac.in (for staff). GNDEC conducts its own autonomous examinations. Mid-Semester Exams (MSE) and End-Semester Exams are held as per the academic calendar. Historical results from 1956 onwards are available as downloadable PDFs on gndec.ac.in/?q=results. Current semester results are declared on the academics portal.","section":"Results","source_file":"exam.gndec.ac.in"},

{"question":"What is the academic calendar at GNDEC?","answer":"GNDEC follows a semester system: Semester 1 (Odd): January–June. Semester 2 (Even): July–December. Academic activities include: Mid-Semester Exams (MSE-I and MSE-II), End-Semester Exams, Practical Exams, Project Evaluations, Industrial Training. Holiday list for 2026 is available on gndec.ac.in. Timetables are published on department websites.","section":"Academic Calendar","source_file":"gndec.ac.in"},

# ─── RESEARCH ───────────────────────────────────────────────────────────────
{"question":"What research opportunities are available at GNDEC?","answer":"GNDEC has active research programs: Ph.D. programs in all Engineering branches and Management. QIP (Quality Improvement Programme) Centre under AICTE for Ph.D. in Civil, Mechanical, and Electrical Engineering. Research funding from DST (Rs. 1 Crore under FIST Programme), AICTE, and other agencies. TEQIP-II (Rs. 10 Crores from MHRD) and TEQIP-III grants received. Faculty research in AI/ML, power systems, structural engineering, manufacturing, and management. About 7,500 post-graduates have passed out.","section":"Research","source_file":"gndec.ac.in"},

]

os.makedirs("data", exist_ok=True)
with open("data/gndec_facts.json", "w", encoding="utf-8") as f:
    json.dump(FACTS, f, indent=2, ensure_ascii=False)

print(f"✅ Written {len(FACTS)} curated Q&A facts to data/gndec_facts.json")
